AWSTemplateFormatVersion: 2010-09-09
Description: Create custom MSK Configuration
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  MSKClusterConfiguration:
    Description: Amazon MSK cluster Configuration Name
    Type: String
Resources:
  MSKConfiguration:
    Type: AWS::MSK::Configuration
    Properties:
      Name: !Ref MSKClusterConfiguration
      ServerProperties: |
        auto.create.topics.enable=false
        default.replication.factor=3
        min.insync.replicas=2
        num.io.threads=8
        num.network.threads=5
        num.partitions=1
        num.replica.fetchers=2
        replica.lag.time.max.ms=30000
        socket.receive.buffer.bytes=102400
        socket.request.max.bytes=104857600
        socket.send.buffer.bytes=102400
        unclean.leader.election.enable=true
        zookeeper.session.timeout.ms=18000
        transaction.state.log.replication.factor=1
        transaction.state.log.min.isr
